
module.exports= {

    SET_MY_GROUP_LIST: 'SET_MY_GROUP_LIST',
    SET_ALL_GROUP_LIST: 'SET_ALL_GROUP_LIST',
    ENABLE_MY_GROUP_ONFRESH:'ENABLE_MY_GROUP_ONFRESH',
    DISABLE_MY_GROUP_ONFRESH:'DISABLE__MY_GROUP_ONFRESH',
    ENABLE_ALL_GROUP_ONFRESH:'ENABLE_ALL_GROUP_ONFRESH',
    DISABLE_ALL_GROUP_ONFRESH:'DISABLE__ALL_GROUP_ONFRESH',
}
