module.exports={

    DISABLE_COMPETITION_ONFRESH:'DISABLE_COMPETITION_ONFRESH',
    ENABLE_COMPETITION_ONFRESH:'ENABLE_COMPETITION_ONFRESH',
    SET_COMPETITION_LIST:'SET_COMPETITION_LIST',
    SET_COMPETITION_ITEM_LIST:'SET_COMPETITION_ITEM_LIST',
    DISABLE_COMPETITION_ITEM_ONFRESH:'DISABLE_COMPETITION_ITEM_ONFRESH',
    ENABLE_COMPETITION_ITEM_ONFRESH:'ENABLE_COMPETITION_ITEM_ONFRESH',

    SET_COMPETATION:'SET_COMPETATION',
    DISABLE_ACTIVITY_ONFRESH:'DISABLE_ACTIVITY_ONFRESH',
    ENABLE_ACTIVITY_ONFRESH:'ENABLE_ACTIVITY_ONFRESH',
    SET_COMPETITION_SCHEDULELIST:'SET_COMPETITION_SCHEDULELIST'

}

