module.exports={
    DISABLE_COMPETITION_ONFRESH:'DISABLE_COMPETITION_ONFRESH',
    ENABLE_COMPETITION_ONFRESH:'ENABLE_COMPETITION_ONFRESH',
    SET_COMPETITION_LIST:'SET_COMPETITION_LIST',
    SET_COMPETITION_ITEM_LIST:'SET_COMPETITION_ITEM_LIST',
    DISABLE_COMPETITION_ITEM_ONFRESH:'DISABLE_COMPETITION_ITEM_ONFRESH',
    ENABLE_COMPETITION_ITEM_ONFRESH:'ENABLE_COMPETITION_ITEM_ONFRESH',
}

