module.exports={
    SET_COMPETATION:'SET_COMPETATION',
    DISABLE_ACTIVITY_ONFRESH:'DISABLE_ACTIVITY_ONFRESH',
    ENABLE_ACTIVITY_ONFRESH:'ENABLE_ACTIVITY_ONFRESH',
    SET_COMPETITION_SCHEDULELIST:'SET_COMPETITION_SCHEDULELIST',
    DISABLE_COMPETITION_ONFRESH:'DISABLE_COMPETITION_ONFRESH',
    ENABLE_COMPETITION_ONFRESH:'ENABLE_COMPETITION_ONFRESH'

}

