
module.exports={
    DISTRIBUTE_COURSE:'DISTRIBUTE_COURSE',
    ON_COURSES_UPDATE:'ON_COURSES_UPDATE',
    DISABLE_MY_COURSES_ONFRESH:'DISABLE_MY_COURSES_ONFRESH',
    ON_MY_COURSES_UPDATE:'ON_MY_COURSES_UPDATE',
    ON_CUSTOM_COURSE_UPDATE:'ON_CUSTOM_COURSE_UPDATE',
    SET_MY_CUSTOM_COURSES:'SET_MY_CUSTOM_COURSES',
    ENABLE_MY_CUSTOM_COURSES_ONFRESH:'ENABLE_MY_CUSTOM_COURSES_ONFRESH',
    DISABLE_MY_CUSTOM_COURSES_ONFRESH:'DISABLE_MY_CUSTOM_COURSES_ONFRESH',
    ON_COURSES_OF_COACH_UPDATE:'ON_COURSES_OF_COACH_UPDATE',
    ENABLE_COURSES_OF_COACH_ONFRESH:'ENABLE_COURSES_OF_COACH_ONFRESH',
    DISABLE_COURSES_OF_COACH_ONFRESH:'DISABLE_COURSES_OF_COACH_ONFRESH',


}
