
module.exports={
    DISTRIBUTE_COURSE:'DISTRIBUTE_COURSE',
    ON_COURSES_UPDATE:'ON_COURSES_UPDATE',
    DISABLE_MY_COURSES_ONFRESH:'DISABLE_MY_COURSES_ONFRESH',
    ON_MY_COURSES_UPDATE:'ON_MY_COURSES_UPDATE',
    ON_CUSTOM_COURSE_UPDATE:'ON_CUSTOM_COURSE_UPDATE',
}
