/**
 * Created by youli on 2017/9/18.
 */


module.exports={
    'NOTIFICATION_RECVED':'NOTIFICATION_RECVED',
    'MAKE_MESSAGE_POP':'MAKE_MESSAGE_POP',
    'ON_MESSAGE_CLOSE':'ON_MESSAGE_CLOSE',
    'UPDATE_NOTIFICATIONS':'UPDATE_NOTIFICATIONS'
}
