
module.exports= {
    SET_NOTICE_LIST:'SET_NOTICE_LIST',
    DISABLE_NOTICE_ONFRESH:'DISABLE_NOTICE_ONFRESH',
    ENABLE_NOTICE_ONFRESH:'ENABLE_NOTICE_ONFRESH',
    SET_NOTICE_MEMBER_LIST:'SET_NOTICE_MEMBER_LIST',
    DISABLE_NOTICE_MEMBER_ONFRESH:'DISABLE_NOTICE_MEMBER_ONFRESH',
    ENABLE_NOTICE_MEMBER_ONFRESH:'ENABLE_NOTICE_MEMBER_ONFRESH',
}
