/**
 * Created by danding on 17/6/2.
 */
module.exports={
    ACCESS_TOKEN_ACK:'ACCESS_TOKEN_ACK',
    UPDATE_PERSON_INFO:'UPDATE_PERSON_INFO',
    UPDATE_CERTIFICATE:'UPDATE_CERTIFICATE',
    UPDATE_USERTYPE:'UPDATE_USERTYPE',
    ON_USER_NAME_UPDATE:'ON_USER_NAME_UPDATE',
    ON_PER_NAME_UPDATE:'ON_PER_NAME_UPDATE',
    ON_WECHAT_UPDATE:'ON_WECHAT_UPDATE',
    ON_PER_ID_CARD_UPDATE:'ON_PER_ID_CARD_UPDATE'
}
